queue_rules:
  - name: default
    conditions:
      - "check-success=ci/circleci: build-and-test"

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - "check-success=ci/circleci: build-and-test"
      - label=ready-to-merge
    actions:
      queue:
        name: default
        commit_message: default
