queue_rules:
  - name: default
    conditions:
      - "check-success=ci/circleci: build-and-test"

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - and:
          - base=main
          - label=ready-to-merge
    actions:
      queue:
        name: default
