queue_rules:
  - name: default
    conditions:
      - check-success=build-and-test

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - and:
          - base=main
          - label=ready-to-merge
          - check-success=build-and-test
    actions:
      queue:
        name: default
